site_name: pyperSpec Documentation
site_description: Python package for hyperspectral data analysis
site_url: https://r-hyperspec.github.io/pyperspec/
repo_url: https://github.com/r-hyperspec/pyperspec
repo_name: r-hyperspec/pyperspec

# See https://squidfunk.github.io/mkdocs-material/setup/ for more options
theme:
  name: "material"
  language: en
  features:
    - content.code.copy
    # - content.tabs.link
    - content.code.annotate
    # - navigation.tabs
    - navigation.instant
    - navigation.instant.prefetch
    - navigation.instant.preview
    - navigation.instant.progress
    - navigation.path
    - navigation.sections
    - navigation.top
    - navigation.tracking
    - search.suggest
    - toc.follow
  palette: 
    # Palette toggle for light mode
    - scheme: default
      toggle:
        icon: material/brightness-7 
        name: Switch to dark mode
    # Palette toggle for dark mode
    - scheme: slate
      toggle:
        icon: material/brightness-4
        name: Switch to light mode
  # logo: 'logo-white.svg'
  favicon: "https://avatars.githubusercontent.com/u/66628186?s=48&v=4"

plugins:
  - search
  - exclude:
      glob:
      - plugins/*
      - __pycache__/*
      - .git/*
      - .pytest_cache
  # https://mkdocstrings.github.io/python/usage/configuration/general/
  - mkdocstrings:
      handlers:
        python:
          options:
            heading_level: 2
            parameter_headings: true
            show_root_heading: true
            show_category_heading: true
            show_symbol_type_heading: true
            show_symbol_type_toc: true
            group_by_category: true
            summary: true
            docstring_style: numpy
            members_order: source

markdown_extensions:
  - attr_list
  - admonition
  - pymdownx.details
  - pymdownx.superfences
  - pymdownx.pathconverter
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.snippets:
      base_path:
      - docs
      - README.md
      check_paths: true
  - pymdownx.tabbed:
      alternate_style: true
  - pymdownx.tasklist:
      custom_checkbox: true
  - toc:
      permalink: true
  - tables

watch:
  - docs
  - pyspc
  - README.md

nav:
  - Home: index.md
  - Getting Started:
    - Installation: installation.md
    - Quick Start: quickstart.md
    - Basic Concepts: concepts.md
  - User Guide:
    - Data Manipulation: user-guide/manipulation.md
    - Hyperspectal images and multidimensional data: user-guide/hyperspectral.md
    - Preprocessing: user-guide/preprocessing.md
    - Visualization: user-guide/visualization.md
    - Import/Export: user-guide/io.md
  # - Examples:
  #   - Basic Usage: examples/basic.md
  - API Reference:
    - SpectraFrame: api-spectraframe.md
    - Peaks: api-peaks.md
    - Spikes: api-spikes.md
    - Utils: api-utils.md
